notifications:
  slack: techholding:GqgzZRTshSxSAgjseIza5oRj
  
  on_success: change # default: always
  
  on_failure: always # default: always
jobs:
  include:
    - # require the branch name to be master (note for PRs this is the base branch name)
      if: branch = master
