notifications:
  slack: techholding:GqgzZRTshSxSAgjseIza5oRj
  
  template:
    - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch} in PR <%{pull_request_url}|#%{pull_request_number}> by %{author} %{result} in %{duration}"
    
  on_success: change # default: always
  
  on_failure: always # default: always
